name: maven-oidc

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write

env:
  CLOUDSMITH_ORG: iduffy-demo
  CLOUDSMITH_REPO: default
  CLOUDSMITH_SERVICE_SLUG: github-c3xe

jobs:
  maven-oidc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven
      - working-directory: maven-example
        run: |
          pip install "git+https://github.com/cloudsmith-io/cloudsmith-cli.git@iduffy/credential-helper-maven"
          cloudsmith credential-helper install maven
          eval "$(cloudsmith credential-helper shell-init)"
          mvn -B clean deploy
